version: '3.8'
services:
  backend : 
    build : ./backend
    env_file :
      - ./backend/.env
    ports : 
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306:3306"
    volumes:
        - "./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend